project: dot
providers:
  google_secretmanager:
    env:
      OPENAI_KEY:
        path: projects/vfarcic/secrets/openai-key/versions/2
      EMAIL_PASSWORD:
        path: projects/vfarcic/secrets/app-email-password/versions/1