project: dot
providers:
  google_secretmanager:
    env:
      OPENAI_KEY:
        path: projects/vfarcic/secrets/openai-key/versions/2
      EMAIL_PASSWORD:
        path: projects/vfarcic/secrets/app-email-password/versions/1
      YOUTUBE_API_KEY:
        path: projects/vfarcic/secrets/youtube-api-key/versions/1
      YOUTUBE_TOKEN:
        path: projects/vfarcic/secrets/youtube-token/versions/1
      TWITTER_API_KEY:
        path: projects/vfarcic/secrets/twitter-api-key/versions/2
      TWITTER_API_SECRET_KEY:
        path: projects/vfarcic/secrets/twitter-api-secret/versions/2
      TWITTER_BEARER_TOKEN:
        path: projects/vfarcic/secrets/twitter-bearer-token/versions/1
      TWITTER_ACCESS_TOKEN:
        path: projects/vfarcic/secrets/twitter-access-token/versions/1
      TWITTER_ACCESS_TOKEN_SECRET:
        path: projects/vfarcic/secrets/twitter-access-token-secret/versions/1