project: dot
providers:
  google_secretmanager:
    env:
      AI_KEY:
        path: projects/vfarcic/secrets/azure-openai-key/versions/1
      EMAIL_PASSWORD:
        path: projects/vfarcic/secrets/app-email-password/versions/1
      YOUTUBE_API_KEY:
        path: projects/vfarcic/secrets/youtube-api-key/versions/1
      YOUTUBE_TOKEN:
        path: projects/vfarcic/secrets/youtube-token/versions/1
