email:
  from: viktor@farcic.com
  thumbnailTo: viktor@farcic.com
  editTo: viktor@farcic.com
  financeTo: devopstoolkit@acme.com
ai:
  endpoint: https://dotaisweden.openai.azure.com
  deployment: gpt-4-1106-preview
hugo:
  path: ../devopstoolkit-live/
youtube:
  channelId: UCfz8x0lVzJpb_dgWm9kPVrw
bluesky:
  identifier: vfarcic.bsky.social
  url: https://bsky.social/xrpc