prepublish:
    completed: 12
    total: 34
publish:
    completed: 1
    total: 17
projectname: dsds
projecturl: acme.com
sponsored: ""
sponsoredemails: []
sponsorshipblocked: ""
subject: ""
date: 2030-01-01T16:00
code: true
screen: true
head: true
thumbnails: true
diagrams: true
title: ""
description: ""
tags: ""
descriptiontags: ""
location: fff
tagline: ""
taglineideas: ""
otherlogos: ""
screenshots: false
requestthumbnail: false
thumbnail: ""
members: ""
animations: ""
requestedit: true
movie: false
timecodes: ""
gist: ""
relatedvideos: ""
playlists: []
uploadvideo: ""
videoid: ""
tweet: ""
tweetposted: false
linkedinposted: false
slackposted: false
redditposted: false
hnposted: false
tcposted: false
youtubehighlight: false
youtubecomment: false
youtubecommentreply: false
slides: false
gde: false
reporeadme: false
twitterspace: false
notifiedsponsors: false
